version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
    - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local